/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package progjarcc;

/**
 *
 * @author Owner
 */
import java.io.IOException;
import sun.net.*;
import java.net.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
public class GUIClient extends javax.swing.JFrame {
private MulticastSocket s;
    public MulticastClient client = new MulticastClient();
    private static String group = "224.0.0.3";
    public ButtonGroup jawaban;
    /**
     * Creates new form GUIClient
     */
    private void groupButton(){
        jawaban = new ButtonGroup();
        jawaban.add(optA);
        jawaban.add(optB);
        jawaban.add(optC);
        jawaban.add(optD);
        
    }
    public GUIClient(MulticastSocket sock) {
        initComponents();
        groupButton();
        this.s = sock;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        askUsername = new javax.swing.JDialog();
        username = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        submitUsername = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        chatBox = new javax.swing.JTextArea();
        exitButton = new javax.swing.JButton();
        optA = new javax.swing.JRadioButton();
        optB = new javax.swing.JRadioButton();
        optC = new javax.swing.JRadioButton();
        optD = new javax.swing.JRadioButton();
        kirimJawaban = new javax.swing.JButton();

        askUsername.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);

        username.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("username");

        submitUsername.setText("submit");
        submitUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitUsernameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout askUsernameLayout = new javax.swing.GroupLayout(askUsername.getContentPane());
        askUsername.getContentPane().setLayout(askUsernameLayout);
        askUsernameLayout.setHorizontalGroup(
            askUsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(askUsernameLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(username)
                .addGap(81, 81, 81))
            .addGroup(askUsernameLayout.createSequentialGroup()
                .addGroup(askUsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(askUsernameLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(askUsernameLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(submitUsername)))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        askUsernameLayout.setVerticalGroup(
            askUsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(askUsernameLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(submitUsername)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        chatBox.setColumns(20);
        chatBox.setRows(5);
        jScrollPane1.setViewportView(chatBox);

        exitButton.setText("Give up");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        optA.setText("A");
        optA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optAActionPerformed(evt);
            }
        });

        optB.setText("B");
        optB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optBActionPerformed(evt);
            }
        });

        optC.setText("C");
        optC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optCActionPerformed(evt);
            }
        });

        optD.setText("D");
        optD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optDActionPerformed(evt);
            }
        });

        kirimJawaban.setText("Submit");
        kirimJawaban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kirimJawabanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(optA)
                        .addGap(24, 24, 24)
                        .addComponent(optB)
                        .addGap(29, 29, 29)
                        .addComponent(optC)
                        .addGap(29, 29, 29)
                        .addComponent(optD)
                        .addGap(18, 18, 18)
                        .addComponent(kirimJawaban)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optA, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(optB)
                    .addComponent(optC)
                    .addComponent(optD)
                    .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kirimJawaban, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void submitUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitUsernameActionPerformed
        // TODO add your handling code here:
        this.client.setUsername(this.username.getText());
        askUsername.setEnabled(false);
        askUsername.setVisible(false);
        
    }//GEN-LAST:event_submitUsernameActionPerformed

    private void optAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optAActionPerformed

    private void optBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optBActionPerformed

    private void optCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optCActionPerformed

    private void optDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optDActionPerformed

    private void kirimJawabanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kirimJawabanActionPerformed
        // TODO add your handling code here:
        String ans;
        if(this.optA.isSelected()){
            ans = this.optA.getText();
        }else if(this.optB.isSelected()){
            ans = this.optB.getText();
        }else if(this.optC.isSelected()){
            ans = this.optC.getText();
        }else{
            ans = this.optD.getText();
        }
        
        client.sendMessage("*ANS#"+ans+"#"+client.getNama());
        
        clearChatBox();
        this.jawaban.clearSelection();
        this.chatBox.append("Anda sudah mengirim jawaban\nMenunggu soal selanjutnya...");
        
    }//GEN-LAST:event_kirimJawabanActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        this.client.sendMessage("*CLOSE CLIENT#"+client.getNama());
        try {
            // TODO add your handling code here:
           s.leaveGroup(InetAddress.getByName(group));
        } catch (UnknownHostException ex) {
            Logger.getLogger(GUIClient.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(GUIClient.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        s.close();
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GUIClient().setVisible(true);
//            }
//        });
    }

    public void updateChatbox(String params){
        this.chatBox.append(params);
    }
    
    public void showAskUsername(){
        this.askUsername.setEnabled(true);
        this.askUsername.setVisible(true);
    }
    
    public void clearChatBox(){
        this.chatBox.setText("");
    }
    
    public void enableOption(){
        this.kirimJawaban.setEnabled(true);
        this.optA.setEnabled(true);
        this.optB.setEnabled(true);
        this.optC.setEnabled(true);
        this.optD.setEnabled(true);
    }
    
    public void disableOption(){
        this.kirimJawaban.setEnabled(false);
        this.optA.setEnabled(false);
        this.optB.setEnabled(false);
        this.optC.setEnabled(false);
        this.optD.setEnabled(false);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog askUsername;
    private javax.swing.JTextArea chatBox;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kirimJawaban;
    private javax.swing.JRadioButton optA;
    private javax.swing.JRadioButton optB;
    private javax.swing.JRadioButton optC;
    private javax.swing.JRadioButton optD;
    private javax.swing.JButton submitUsername;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
